---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: default
  name: demoweb
  labels:
    app: demoweb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demoweb
  template:
    metadata:
      labels:
        app: demoweb
    spec:
      containers:
        - name: demoweb
          image: nginx:latest
          ports:
            - name: web
              containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: demoweb
spec:
  type: ClusterIP      
  ports:
    - protocol: TCP
      name: web
      port: 80
  selector:
    app: demoweb

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: demoweb
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: demoweb
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
---
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: demoweb
spec:
 parentRefs:
  - kind: Gateway
    name: external-http
    namespace: gateways
 hostnames:
 - "demoweb.devfest.spgo.se"
 rules:
 - backendRefs:
   - name: demoweb
     port: 80    