---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: kcc-demo-svc
  namespace: kcc
spec:
  member: serviceAccount:kcc-demo-svc@wtfpr-develop-in-gcp-kuu.iam.gserviceaccount.com
  role: roles/owner
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: projects/wtfpr-develop-in-gcp-kuu
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: wtfpr-develop-in-gcp-kuu
  name: kcc-demo-svc
  namespace: kcc
spec:
  displayName: KCC Demo Service-account